### ISSUE TITLE
bug with jQuery 3.x

### ISSUE THREAD

**Issue by ctoicqtao** [ankitjain28may/autoscroll.js#4]
There is a bug when use jQuery 3.x.

`this.autoScroll = $(this.selector);`

There is no "selector" prop in "this" object.

Can you fix it?

thanks.

**Comment by ctoicqtao** [comment]
i fix it like this.

`this.autoScroll = $(this).eq(0);`

but i think it's not very good.

**Comment by ankitjain28may** [comment]
Ya sure i will look into it.. Thanks for finding a bug..!

**Comment by ankitjain28may** [comment]
It is fixed thanks for the catch..!

**Comment by ctoicqtao** [comment]
thanks
